version: "3.8"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.7
    ports:
      - 8082:8082
      - 8086:8086
      - 8089:8089
    volumes:
      - ./influxdb-data:/var/lib/influxdb
      - ./conf/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./conf/influxdb/prometheus.iql:/docker-entrypoint-initdb.d/prometheus.iql:ro
    environment:
      - INFLUXDB_DB=prometheus
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_USER=prometheus
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_READ_USER=grafana
      - INFLUXDB_READ_USER_PASSWORD=password

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.23.0
    ports:
      - 9090:9090
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--log.level=debug"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention=1h"
      - "--web.enable-admin-api"
    depends_on:
      - "influxdb"

  grafana:
    container_name: grafana
    image: grafana/grafana:7.3.4
    ports:
      - 3000:3000
    volumes:
      - ./conf/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./conf/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - "prometheus"
